### ISSUE TITLE
API reference for 0.17.0 failed to build; reference for 0.17.1 does not exist

### ISSUE THREAD

**Issue by ovibos** [lfairy/maud#103]
The [docs.rs API reference linked in the README.md](https://docs.rs/maud/)  redirects to the latest version at the time of writing this issue, [0.17.1](https://docs.rs/maud/0.17.1), which is just a blank page with the message "The requested resource does not exist". Upon further investigation, it looks like while v0.16.2 exists and is fine, v0.17.0 failed to build. [Here](https://docs.rs/crate/maud/0.17.0/builds/66832) is the build logs for 0.17.0.

The interesting part:

```
error[E0277]: the trait bound `proc_macro::TokenTreeIter: std::clone::Clone` is not satisfied
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.17.0/src/parse.rs:36:5
   |
36 |     input: TokenTreeIter,
   |     ^^^^^^^^^^^^^^^^^^^^ the trait `std::clone::Clone` is not implemented for `proc_macro::TokenTreeIter`
   |
   = note: required by `std::clone::Clone::clone`
```

**Comment by lfairy** [comment]
Thanks for the report!

That's probably because docs.rs was using an older version of the compiler. The `Clone` impl for `TokenTreeIter` (rust-lang/rust#43280) landed on Jul 24, but the compiler listed in that log dates from Jul 10.

I have reported the issue at https://github.com/onur/docs.rs/issues/23#issuecomment-333284541.

**Comment by lfairy** [comment]
https://docs.rs/maud/0.17.1/maud/ works now
