### ISSUE TITLE
Build fails with recent nightly

### ISSUE THREAD

**Issue by sanmai-NL** [lfairy/maud#119]
```
target/debug/deps/libmaud_macros-e1339a2e904a7808.so: undefined symbol: __rustc_plugin_registrar_b08239990af0cd9d14cdf2a0d3d005ee__
```
# Meta
```
rustc 1.25.0-nightly (90eb44a58 2018-01-29)
binary: rustc
commit-hash: 90eb44a5897c39e3dff9c7e48e3973671dcd9496
commit-date: 2018-01-29
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

**Comment by lfairy** [comment]
Have you tried `cargo clean`?

The Travis build is passing, so I suspect it's something on your end.

**Comment by sanmai-NL** [comment]
Yeah, I had, and have again. 

The issue only disappears after removing from the source code:
```rust
#![plugin(maud_macros)]
```

That line is no longer current, so it’s a bug in my code. Apparently this issue only appears since a recent compiler change.

**Comment by thePalindrome** [comment]
I'd like to re-open this, seeing as "don't use this plugin" isn't *really* a solution, and it's causing build errors for koto-bank/zeph. 
currently on 1.28.0-nightly.
It could *conceivably* be an issue on zeph's end, but the cargo output (and where the plugin delcaration is) suggest it's in maud:

Error:
`debug/deps/libmaud_macros-47a7b704f937589f.so: undefined symbol: __rustc_plugin_registrar_83d325d51709f388a4d3c187f8e5cca5__`
the line in question is simply
`#![plugin(maud_macros)]`

So I'm not sure entirely what the problem is.

**Comment by lfairy** [comment]
Maud is a proc macro now, not a compiler plugin (they're different things!), so you shouldn't be importing it like that.

The correct way to use it is documented in [the book](https://maud.lambda.xyz/getting_started.html):

```rust
#![feature(proc_macro)]

extern crate maud;
use maud::html;
```

**Comment by thePalindrome** [comment]
Alright, I'll report this downstream, although at this rate, I probably just go my own, thanks for being so fast!
