### ISSUE TITLE
Subtemplates, inheritance and @call

### ISSUE THREAD

**Issue by max-frai** [lfairy/maud#133]
Hi, amazing lib! I rewrote all my templates to this syntax but have now a question. What is the right way to organize subtemplating? I found your old post on rust forum where you suggest to use `@call` but now it's unknown keyword. I dig into sources and didn't find any references to code which should process this statement.
So for now the only case I see is to just pass string subtemplate which also generated by html macro and include it as variable in parent template in needed place.

**Comment by lfairy** [comment]
Thanks! I think you're on the right track 🙂

A `html! { .. }` expression evaluates to a [`Markup`](https://docs.rs/maud/0.17.2/maud/type.Markup.html) object, which implements the [`Render` trait](https://docs.rs/maud/0.17.2/maud/trait.Render.html). This means that you can build subtemplates by including the result of a `html!` block in another `html!` block. See [this file](https://github.com/lfairy/karkinos/blob/master/src/views.rs) for an example of how this can be done.

I admit, it's not obvious from the docs that you can do this. Happy to take suggestions on how to improve it.

**Comment by max-frai** [comment]
That's what I need.
I think it's okay but docs may be better for this. Probably each newcomer will need such functionality and everyone starts from docs.
For example, also from your example file I found that it's possible to output PreEscaped multiline string with r#"..."# and it's not mentioned in the docs :)

**Comment by lfairy** [comment]
Unfortunately, I don't think that kind of syntax is practical at the moment.

Procedural macros cannot maintain internal state across calls (at least not in a consistent way), so we wouldn't be able to link the `$form::text` call in one file to the corresponding `fn text` definition.

We can get around this by defining `form::text` as a macro. But that would make errors much harder to read. For example, suppose that you made a type error in the definition of `text`. Then the compiler would raise an separate error for each invocation of the macro, instead of once at the definition.

If performance is an issue, I think taking in an explicit buffer parameter (#90) would be a simpler solution. Note that a large template takes ~ 100 ns to run already, so I doubt that it is an issue in most cases.
