### ISSUE TITLE
Suggestion: split apart the templating from the HTML

### ISSUE THREAD

**Issue by ivanbakel** [lfairy/maud#154]
This crate is really impressive!

The general templating code looks really useful for some other outputs as well, and I'd really like to adapt it for a similar markdown crate. Would you be interested in having some changes to `maud_macros` to allow for different output types and content macros?

I imagine splitting off the templating, like `@if`, slicing, and flags, into a system that you could use for all kinds of content.

**Comment by ivanbakel** [comment]
For an example, I've done some of the changes I imagined on [a branch](https://github.com/ivanbakel/maud/tree/common_templating). The idea would be to allow macro parsers in other formats to implement the `engine::Parser` trait, as the `html` parser does, to use the helpers for parsing e.g. splices and blocks. 

The result has mostly been moving code around, but the engine code could be exported by the crate and the html-specific stuff could be a default feature to allow for reuse elsewhere.

**Comment by lfairy** [comment]
Hi @ivanbakel -- can you tell me a bit more about what kind of Markdown crate you're building?

I've been thinking about refactoring the parser to allow for creating DOM nodes instead of strings, as part of the push toward Rust in the browser (wasm). But it looks like you're taking it in a different direction.

I've always seen Maud as a library for HTML; most of the features / design decisions are oriented around that vision. If you'd like to transform it into something else, then that's cool, but I wouldn't call it Maud anymore.

**Comment by ivanbakel** [comment]
The goal is to have a crate which provides Maud-style templating for pulldown_cmark's representation of markdown. The parsing would be independent of Maud's, since you can constrain  markdown elements more easily than HTML, I think - but the syntax for content-independent templating functionality, like splices, let bindings, and control flow, would be the same. 

I think the two refactorings can go together. What I'm trying to do is separate out the content-independent functionality so that it can be reused with many kinds of syntax and output - so ideally, you would be able to make the switch from Strings to DOM nodes by just changing HTML-specific code: change the associated type on the `Generator` trait impl, and the code for outputting elements, and the way you combine sequential elements in a block. Then, for free from the content-independent engine, you'd automatically get for loops, splices,  etc. for the new output.
