### ISSUE TITLE
Prefix `else` with @ is not necessary

### ISSUE THREAD

**Issue by J-F-Liu** [lfairy/maud#63]
Better to write
```
        @if let Some(name) = user {
            (name)
        } @else {
            "stranger"
        }
```
as
```
        @if let Some(name) = user {
            (name)
        } else {
            "stranger"
        }
```
Like this: http://www.w3schools.com/asp/razor_cs_logic.asp

**Comment by lfairy** [comment]
This idea has been suggested before. Unfortunately, this change will make it impossible to support XML templates in the future (#62), since such a document might have an element named `<else>`. Moreover, the HTML5 standard is always changing; there's a chance that they'll add an `<else>` element in the future.

For these reasons I'll close this issue as wontfix.
