### ISSUE TITLE
Context-aware escaping

### ISSUE THREAD

**Issue by DemiMarie** [lfairy/maud#88]
Maud claims to [not need context-aware escaping](https://maud.lambda.xyz/faq.html#why-doesnt-maud-implement-context-aware-escaping).  However, context-aware escaping could make Maud easier to use in certain contexts.  This is especially true for small pages, where having to move everything to separate files is a hassle.  Furthermore, the color example and the URL example *require* context-aware escaping: I don't see any way to avoid needing CSS/URL (respectively) aware escaping.

**Comment by lfairy** [comment]
In Rust, you would define a `struct Color([u8; 4]);` with a `Display` impl that always emits a safe color.

Similarly, for URLs you would parse the user input with [`url`](https://crates.io/crates/url) and enforce safe URL schemes there. You'd want to do that anyway, to give early feedback when the user submits an unsafe URL.

---

I am hesitant to do additional escaping without the developer saying so, because it breaks the simple mental model that Maud currently has. What used to be "everything is HTML escaped"  would then become "everything is HTML escaped, *and also* `style` is also CSS escaped, *and also* if you include a `url('...')` in there then..." I do not consider this complexity a good trade-off for the kind of small-scale development that Maud is designed for.

That's ignoring XML support (#62) -- I don't see how context-aware escaping will interact with that.

My preferred solution is to provide extensive static checks (#66), with the ability to disable these checks selectively when the developer thinks what they're doing is safe. This explicit approach is what Rust takes as a whole, and what I think is best for this library going forward.
