### ISSUE TITLE
Proc macro panic when class name contains numbers

### ISSUE THREAD

**Issue by Arcterus** [lfairy/maud#98]
More specifically, panics occur when using dot notation for classes such as the following:
```css
.is-4by3
.is-3
```
Here's an example function that triggers the panic:
```rust
fn test() {
   let _ = html! { figure .is-4by3 { } };
}
```

**Comment by lfairy** [comment]
I think this is because Maud expects an identifier token there, but sees a number literal instead. (The input `4by3` is parsed as the number `4` with a `by3` type suffix.)

The fix, then, would be to accept number literals as well as identifiers as part of a class or ID name. 
Note that we'll need to be careful with float literals, otherwise `#2.3` would expand to `class="2.3"` instead of `id="2" class="3"` as we'd expect. I'll be happy to accept a PR for this.

**Comment by albe-rosado** [comment]
shouldn't classes and ids separated by a space (ie. #2 .3)? there is no way you could guess from class-"2.3" and class="2" id="3".

**Comment by bb010g** [comment]
I'd think it would be simpler to just have complex strings like that require quoting, like `figure .'is-4by3' { }`.

**Comment by albe-rosado** [comment]
I like that, @lfairy what do you think?

**Comment by lfairy** [comment]
Yeah that's a good point. I'll be happy with @bb010g's solution (assuming you meant `."is-4by3"`, since single quotes won't parse)

**Comment by albe-rosado** [comment]
yeah that makes sense and looks nice

**Comment by lfairy** [comment]
Closing in favor of #128, which includes this feature (and more).
